on:
  push:
    branches:
      - develop

env:
  DomeProject: src/Pug.Dome/Pug.Dome.csproj

jobs:
  build:
    name: Build Projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Authenticates packages to push to GPR
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/PugCS/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      # Build, pack, and publish Pug.Dome NuGet package
      - name: Build Pug.Dome project
        run: dotnet build --nologo --configuration debug ${{env.DomeProject}}
  
